---
- hosts: all
  tasks:

    - name: copy artifacts
      copy:
        src: .
        dest: stack

    - name: build stack
      shell: cd stack | sudo docker compose build

    - name: run stack
      shell: cd stack | sudo docker compose up -d